version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
