version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    depends_on:
      - backend

  database:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - database:/var/lib/mysql-database

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:password@database:3306/university
      JWT_COOKIE_EXPIRE: 30
      JWT_SECRET: ThisIsJWTSecret
      JWT_EXPIRE: 30d
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  database:
