import './globals.css'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { authOptions } from './api/auth/[...nextauth]/route'
import NextAuthProvider from '@/providers/NextAuthProvider'
import { getServerSession } from 'next-auth'

export const metadata = {
  title: 'University user management system',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }) {
  const nextAuthSession = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <NextAuthProvider session={nextAuthSession}>
          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          <div className="bg-gradient-to-br from-cyan-500 to-sky-600 min-h-screen">{children}</div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
