import './globals.css'

export const metadata = {
  title: 'University user management system',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gradient-to-br from-cyan-500 to-sky-600 min-h-screen">{children}</div>
      </body>
    </html>
  )
}
